function Etot = TotEnergy(I1,I2,d1,d2,g,l1,m1,m2,th1,th2,thdot1,thdot2)
%TOTENERGY
%    ETOT = TOTENERGY(I1,I2,D1,D2,G,L1,M1,M2,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    06-Oct-2014 12:39:50

t2 = thdot1+thdot2;
t4 = th1+th2;
t7 = cos(th1);
t10 = cos(t4);
t3 = d2.*t2.*t10+l1.*t7.*thdot1;
t9 = sin(th1);
t5 = d2.*t2.*sin(t4)+l1.*t9.*thdot1;
t6 = thdot1.^2;
t8 = d1.^2;
Etot = I1.*t6.*(1.0./2.0)+m1.*(t6.*t7.^2.*t8+t6.*t8.*t9.^2).*(1.0./2.0)+I2.*t2.^2.*(1.0./2.0)+m2.*(t3.^2+t5.^2).*(1.0./2.0)+g.*m2.*(d2.*t10+l1.*t7)+d1.*g.*m1.*t7;
