function eqn2 = Thdotdot2(Fdx,Fdy,I1,I2,T1,T2,d1,d2,g,l1,l2,m1,m2,th1,th2,thdot1,thdot2)
%THDOTDOT2
%    EQN2 = THDOTDOT2(FDX,FDY,I1,I2,T1,T2,D1,D2,G,L1,L2,M1,M2,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    24-Nov-2014 12:33:29

t2 = d2.^2;
t3 = l1.^2;
t4 = d1.^2;
t5 = m2.^2;
t6 = th1+th2;
t7 = sin(t6);
t8 = thdot1.^2;
t9 = sin(th2);
t10 = cos(th1);
t11 = sin(th1);
t12 = th1-th2;
t13 = cos(th2);
t14 = th2.*2.0;
t15 = thdot2.^2;
t16 = sin(t14);
t17 = sin(t12);
t18 = cos(t6);
t19 = t14+th1;
t20 = sin(t19);
eqn2 = -(I1.*T2.*-2.0+I2.*T1.*2.0-I2.*T2.*2.0+T1.*m2.*t2.*2.0-T2.*m2.*t2.*2.0-T2.*m1.*t4.*2.0-T2.*m2.*t3.*2.0-Fdx.*I2.*l1.*t10.*2.0+Fdx.*I1.*l2.*t18.*2.0+Fdy.*I1.*l2.*t7.*2.0-Fdy.*I2.*l1.*t11.*2.0-I1.*d2.*g.*m2.*t7.*2.0+I2.*d1.*g.*m1.*t11.*2.0+I2.*g.*l1.*m2.*t11.*2.0-Fdx.*d2.*m2.*t3.*t18-Fdy.*d2.*m2.*t3.*t7-Fdy.*d2.*m2.*t3.*t17+T1.*d2.*l1.*m2.*t13.*2.0-T2.*d2.*l1.*m2.*t13.*4.0-Fdx.*l1.*m2.*t2.*t10.*2.0+Fdx.*l2.*m1.*t4.*t18.*2.0+Fdx.*l2.*m2.*t3.*t18.*2.0+Fdy.*l2.*m1.*t4.*t7.*2.0+Fdy.*l2.*m2.*t3.*t7.*2.0-Fdy.*l1.*m2.*t2.*t11.*2.0-d2.*g.*t3.*t5.*t7+d2.*g.*t3.*t5.*t17+g.*l1.*t2.*t5.*t11-g.*l1.*t2.*t5.*t20+t2.*t3.*t5.*t8.*t16.*2.0+t2.*t3.*t5.*t15.*t16-Fdx.*d2.*m2.*t3.*cos(t12)+t2.*t3.*t5.*t16.*thdot1.*thdot2.*2.0+Fdx.*d2.*l1.*l2.*m2.*cos(t19)+Fdx.*d2.*l1.*l2.*m2.*t10+Fdy.*d2.*l1.*l2.*m2.*t11+Fdy.*d2.*l1.*l2.*m2.*t20+I1.*d2.*l1.*m2.*t8.*t9.*2.0+I2.*d2.*l1.*m2.*t8.*t9.*2.0+I2.*d2.*l1.*m2.*t9.*t15.*2.0-d2.*g.*m1.*m2.*t4.*t7.*2.0+d1.*g.*m1.*m2.*t2.*t11.*2.0+d2.*l1.*t2.*t5.*t8.*t9.*2.0+d2.*l1.*t3.*t5.*t8.*t9.*2.0+d2.*l1.*t2.*t5.*t9.*t15.*2.0+I2.*d2.*l1.*m2.*t9.*thdot1.*thdot2.*4.0+d1.*d2.*g.*l1.*m1.*m2.*t7+d1.*d2.*g.*l1.*m1.*m2.*t17+d2.*l1.*m1.*m2.*t4.*t8.*t9.*2.0+d2.*l1.*t2.*t5.*t9.*thdot1.*thdot2.*4.0)./(I1.*I2.*2.0+I1.*m2.*t2.*2.0+I2.*m1.*t4.*2.0+I2.*m2.*t3.*2.0+t2.*t3.*t5+m1.*m2.*t2.*t4.*2.0-t2.*t3.*t5.*cos(t14));
